remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Jeremy Howard
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Jeremy Howard
