remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: The DataScientist Cookbook
description: Personal projects in my data science journey.

author:
  name: Raghunandan Ramadass
